export const leads = [
  {
    id: 'LEAD-1007',
    source: 'Website',
    customer: 'Green Valley Retail',
    contactPerson: 'Anita Rao',
    mobile: '9876543210',
    email: 'anita@greenvalley.example',
    interestedProducts: ['Water Jar Refill (20L)', 'Water Dispenser - Normal'],
    expectedBudget: 42000,
    expectedClosingDate: '2026-08-18',
    assignedSalesperson: 'Sushil',
    status: 'New',
    createdAt: '2026-08-06',
    notes: 'Requested pricing for monthly supply.',
  },
  {
    id: 'LEAD-1006',
    source: 'Referral',
    customer: 'Shree Medical Store',
    contactPerson: 'Mahesh Patel',
    mobile: '9123456780',
    email: '',
    interestedProducts: ['Water Jar Refill (20L)'],
    expectedBudget: 18500,
    expectedClosingDate: '2026-08-12',
    assignedSalesperson: 'Sushil',
    status: 'Follow-up',
    createdAt: '2026-08-05',
    notes: 'Call after store renovation is complete.',
  },
  {
    id: 'LEAD-1005',
    source: 'Walk-in',
    customer: 'Blue Nest Offices',
    contactPerson: '',
    mobile: '9988776655',
    email: 'ops@bluenest.example',
    interestedProducts: ['Water Dispenser - Hot & Cold', 'Water Jar Refill (20L)'],
    expectedBudget: 67000,
    expectedClosingDate: '',
    assignedSalesperson: 'Neha Sharma',
    status: 'Qualified',
    createdAt: '2026-08-05',
    notes: 'Needs dispenser demo this week.',
  },
]
