export const organizations = [
  {
    id: 'org-1',
    name: 'SAAS Distributors',
    slug: 'saas-distributors',
    plan: 'Enterprise',
    status: 'Active',
    city: 'Bengaluru',
    state: 'Karnataka',
    phone: '+91 80 4567 8901',
    email: 'contact@saasdistributors.in',
    gstNumber: '29AAACA1234F1Z5',
    employeeCount: 24,
    totalUsers: 24,
    mrr: 9999,
    adminName: 'Anita Sharma',
    adminEmail: 'anita@saasdistributors.in',
    createdAt: '2023-02-14',
    subscriptionRenewsAt: '2027-02-14',
  },
  {
    id: 'org-2',
    name: 'Himalayan Springs Co.',
    slug: 'himalayan-springs',
    plan: 'Pro',
    status: 'Active',
    city: 'Dehradun',
    state: 'Uttarakhand',
    phone: '+91 135 265 1122',
    email: 'hello@himalayanspring.in',
    gstNumber: '05AAACH5678G1Z2',
    employeeCount: 11,
    totalUsers: 11,
    mrr: 4999,
    adminName: 'Rajesh Kumar',
    adminEmail: 'rajesh@himalayanspring.in',
    createdAt: '2024-06-01',
    subscriptionRenewsAt: '2026-06-01',
  },
  {
    id: 'org-3',
    name: 'CrystalDrop Beverages',
    slug: 'crystaldrop-beverages',
    plan: 'Free',
    status: 'Inactive',
    city: 'Pune',
    state: 'Maharashtra',
    phone: '+91 20 2345 6789',
    email: 'support@crystaldrop.in',
    gstNumber: '27AAACC9012H1Z8',
    employeeCount: 4,
    totalUsers: 4,
    mrr: 0,
    adminName: 'Priya Singh',
    adminEmail: 'priya@crystaldrop.in',
    createdAt: '2026-06-20',
    subscriptionRenewsAt: '2026-07-20',
  },
  {
    id: 'org-4',
    name: 'BlueWave Water Co.',
    slug: 'bluewave-water',
    plan: 'Pro',
    status: 'Suspended',
    city: 'Ahmedabad',
    state: 'Gujarat',
    phone: '+91 79 4123 5566',
    email: 'accounts@bluewavewater.in',
    gstNumber: '24AAACB3456J1Z9',
    employeeCount: 9,
    totalUsers: 9,
    mrr: 4999,
    adminName: 'Vikram Patel',
    adminEmail: 'vikram@bluewavewater.in',
    createdAt: '2023-11-05',
    subscriptionRenewsAt: '2026-05-05',
  },
]
