export const quotations = [
  {
    id: 'QT-2026-1003',
    quotationDate: '2026-08-06',
    validUntil: '2026-08-21',
    customer: 'Hotel Grand Meridian',
    billingAddress: 'Hotel Grand Meridian, Bengaluru',
    shippingAddress: 'Hotel Grand Meridian, Bengaluru',
    salesperson: 'Vikram Singh',
    currency: 'INR',
    paymentTerms: 'Net 15',
    deliveryTerms: 'Standard delivery',
    notes: 'Monthly packaged water supply estimate.',
    terms: 'Prices are valid until the quotation expiry date.',
    status: 'Draft',
    items: [
      {
        product: 'Water Jar Refill (20L)',
        sku: 'JR-20L-R',
        description: '20L refill jar',
        quantity: 50,
        uom: 'jar',
        unitPrice: 40,
        discount: 0,
        tax: 12,
      },
    ],
  },
  {
    id: 'QT-2026-1002',
    quotationDate: '2026-08-05',
    validUntil: '2026-08-20',
    customer: 'Sunrise Corporate Park',
    billingAddress: 'Sunrise Corporate Park, Bengaluru',
    shippingAddress: 'Sunrise Corporate Park, Bengaluru',
    salesperson: 'Vikram Singh',
    currency: 'INR',
    paymentTerms: 'Net 30',
    deliveryTerms: 'Delivery within 2 business days',
    notes: '',
    terms: 'Taxes are extra as applicable.',
    status: 'Sent',
    items: [
      {
        product: 'Water Dispenser - Normal (Standard)',
        sku: 'DISP-N',
        description: 'Standard water dispenser',
        quantity: 2,
        uom: 'unit',
        unitPrice: 2800,
        discount: 5,
        tax: 18,
      },
    ],
  },
]
