export const movementTypes = [
  { value: 'opening', label: 'Opening Stock', badge: 'neutral' },
  { value: 'purchase', label: 'Purchase Receipt', badge: 'success' },
  { value: 'sale', label: 'Sales Deduction', badge: 'info' },
  { value: 'adjustment', label: 'Adjustment', badge: 'warning' },
  { value: 'damaged', label: 'Damaged Stock', badge: 'danger' },
  { value: 'expired', label: 'Expired Stock', badge: 'danger' },
  { value: 'return', label: 'Return', badge: 'primary' },
]

const rawStockItems = [
  {
    sku: 'WTR-250',
    productName: 'Water',
    size: '250 ml',
    brand: 'AquaPure',
    category: 'Water',
    unit: 'Bottle',
    openingStock: 1000,
    minStock: 500,
    currentStock: 1500,
    movements: [
      { id: 1, type: 'opening', quantity: 1000, date: '2026-06-01', reference: 'Opening balance', balanceAfter: 1000 },
      { id: 2, type: 'purchase', quantity: 800, date: '2026-06-10', poNumber: 'PO-2024-001', supplier: 'Prime Manufacturing', reference: 'PO-2024-001', balanceAfter: 1800 },
      { id: 3, type: 'sale', quantity: -300, date: '2026-06-15', reference: 'Sales dispatch SO-1042', balanceAfter: 1500 },
    ],
  },
  {
    sku: 'WTR-500',
    productName: 'Water',
    size: '500 ml',
    brand: 'AquaPure',
    category: 'Water',
    unit: 'Bottle',
    openingStock: 600,
    minStock: 500,
    currentStock: 200,
    movements: [
      { id: 1, type: 'opening', quantity: 600, date: '2026-06-01', reference: 'Opening balance', balanceAfter: 600 },
      { id: 2, type: 'sale', quantity: -350, date: '2026-06-12', reference: 'Sales dispatch SO-1047', balanceAfter: 250 },
      { id: 3, type: 'damaged', quantity: -50, date: '2026-06-20', reference: 'Crate damaged in transit', balanceAfter: 200 },
    ],
  },
  {
    sku: 'WTR-1L',
    productName: 'Water',
    size: '1 Litre',
    brand: 'AquaPure',
    category: 'Water',
    unit: 'Bottle',
    openingStock: 500,
    minStock: 300,
    currentStock: 800,
    movements: [
      { id: 1, type: 'opening', quantity: 500, date: '2026-06-01', reference: 'Opening balance', balanceAfter: 500 },
      { id: 2, type: 'purchase', quantity: 400, date: '2026-06-14', poNumber: 'PO-2024-004', supplier: 'Prime Manufacturing', reference: 'PO-2024-004', balanceAfter: 900 },
      { id: 3, type: 'sale', quantity: -100, date: '2026-06-22', reference: 'Sales dispatch SO-1050', balanceAfter: 800 },
    ],
  },
  {
    sku: 'THM-200',
    productName: 'Thums Up',
    size: '200 ml',
    brand: 'Thums Up',
    category: 'Soft Drinks',
    unit: 'Bottle',
    openingStock: 400,
    minStock: 200,
    currentStock: 0,
    movements: [
      { id: 1, type: 'opening', quantity: 400, date: '2026-06-01', reference: 'Opening balance', balanceAfter: 400 },
      { id: 2, type: 'sale', quantity: -380, date: '2026-06-18', reference: 'Sales dispatch SO-1055', balanceAfter: 20 },
      { id: 3, type: 'expired', quantity: -20, date: '2026-06-25', reference: 'Expired batch cleared', balanceAfter: 0 },
    ],
  },
  {
    sku: 'THM-500',
    productName: 'Thums Up',
    size: '500 ml',
    brand: 'Thums Up',
    category: 'Soft Drinks',
    unit: 'Bottle',
    openingStock: 300,
    minStock: 200,
    currentStock: 350,
    movements: [
      { id: 1, type: 'opening', quantity: 300, date: '2026-06-01', reference: 'Opening balance', balanceAfter: 300 },
      { id: 2, type: 'purchase', quantity: 100, date: '2026-06-16', poNumber: 'PO-2024-006', supplier: 'Bottle Suppliers Inc', reference: 'PO-2024-006', balanceAfter: 400 },
      { id: 3, type: 'return', quantity: -50, date: '2026-06-24', reference: 'Customer return RTN-021', balanceAfter: 350 },
    ],
  },
  {
    sku: 'THM-1L',
    productName: 'Thums Up',
    size: '1 Litre',
    brand: 'Thums Up',
    category: 'Soft Drinks',
    unit: 'Bottle',
    openingStock: 200,
    minStock: 150,
    currentStock: 50,
    movements: [
      { id: 1, type: 'opening', quantity: 200, date: '2026-06-01', reference: 'Opening balance', balanceAfter: 200 },
      { id: 2, type: 'sale', quantity: -150, date: '2026-06-19', reference: 'Sales dispatch SO-1058', balanceAfter: 50 },
    ],
  },
  {
    sku: 'THM-2L',
    productName: 'Thums Up',
    size: '2 Litres',
    brand: 'Thums Up',
    category: 'Soft Drinks',
    unit: 'Bottle',
    openingStock: 150,
    minStock: 100,
    currentStock: 120,
    movements: [
      { id: 1, type: 'opening', quantity: 150, date: '2026-06-01', reference: 'Opening balance', balanceAfter: 150 },
      { id: 2, type: 'adjustment', quantity: -30, date: '2026-06-21', reference: 'Cycle count correction', balanceAfter: 120 },
    ],
  },
]

export const stockItems = rawStockItems.map((item) => ({ status: 'active', ...item }))
