import {
  LayoutDashboard,
  Building2,
  CreditCard,
  BarChart3,
  Package,
  Users,
  ShoppingCart,
  PackagePlus,
  Truck,
  Receipt,
  FileText,
  UserCog,
  Settings,
  MapPin,
  Wallet,
  Store,
  Warehouse,
  Car,
  FileSpreadsheet,
  Bell,
  History,
  UserPlus,
  ClipboardList,
  CheckSquare,
  Target,
  Calendar,
  PackageCheck,
  PackageX,
  LogIn,
  LogOut,
  TrendingUp,
  IndianRupee,
  Check,
  XCircle,
  FileCheck,
  DollarSign,
  PieChart,
  UsersRound,
  Activity,
} from 'lucide-react'

export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  SALES_OFFICER: 'sales_officer',
  DELIVERY_PARTNER: 'delivery_partner',
  ACCOUNTANT: 'accountant',
}

export const roleLabels = {
  [ROLES.SUPER_ADMIN]: 'Super Admin',
  [ROLES.ADMIN]: 'Admin',
  [ROLES.SALES_OFFICER]: 'Sales Officer',
  [ROLES.DELIVERY_PARTNER]: 'Delivery Partner',
  [ROLES.ACCOUNTANT]: 'Accountant',
}

export const roleHomePath = {
  [ROLES.SUPER_ADMIN]: '/superadmin/dashboard',
  [ROLES.ADMIN]: '/admin/dashboard',
  [ROLES.SALES_OFFICER]: '/sales/dashboard',
  [ROLES.DELIVERY_PARTNER]: '/delivery/dashboard',
  [ROLES.ACCOUNTANT]: '/accounts/dashboard',
}

export const roleMenus = {
  [ROLES.SUPER_ADMIN]: [
    { label: 'Dashboard', path: '/superadmin/dashboard', icon: LayoutDashboard },
    { label: 'Organizations', path: '/superadmin/organizations', icon: Building2 },
    { label: 'Plans', path: '/superadmin/plans', icon: CreditCard },
    { label: 'Platform Analytics', path: '/superadmin/analytics', icon: Activity },
  ],
  [ROLES.ADMIN]: [
    { label: 'Dashboard', path: '/admin/dashboard', icon: LayoutDashboard },
    { label: 'Company Settings', path: '/admin/company-settings', icon: Store },
    { label: 'Plans', path: '/admin/plans', icon: CreditCard },
    { label: 'User Management', path: '/admin/users', icon: Users },
    { label: 'Products', path: '/admin/products', icon: Package },
    { label: 'Inventory', path: '/admin/inventory', icon: Warehouse },
    { label: 'Vehicle Stock', path: '/admin/vehicle-stock', icon: Car },
    { label: 'Purchases', path: '/admin/purchases', icon: PackagePlus },
    { label: 'Deliveries', path: '/admin/deliveries', icon: Truck },
    { label: 'Expenses', path: '/admin/expenses', icon: Receipt },
    { label: 'Invoices', path: '/admin/invoices', icon: FileText },
    { label: 'Reports', path: '/admin/reports', icon: FileSpreadsheet },
    { label: 'Notifications', path: '/admin/notifications', icon: Bell },
    { label: 'Audit Logs', path: '/admin/audit-logs', icon: History },
    { label: 'Settings', path: '/admin/settings', icon: Settings },
  ],
  [ROLES.ACCOUNTANT]: [
    { label: 'Dashboard', path: '/accounts/dashboard', icon: LayoutDashboard },
    { label: 'Purchase Invoices', path: '/accounts/invoices/purchases', icon: PackagePlus },
    { label: 'Sales Invoices', path: '/accounts/invoices/sales', icon: ShoppingCart },
    { label: 'Record Payment', path: '/accounts/payments/record', icon: Wallet },
    { label: 'Expense Approval', path: '/accounts/expenses/approval', icon: Receipt },
    { label: 'Cash Reconciliation', path: '/accounts/reconciliation/cash', icon: IndianRupee },
    { label: 'Receivables/Payables', path: '/accounts/outstanding', icon: TrendingUp },
    { label: 'GST Summary', path: '/accounts/gst', icon: FileCheck },
    { label: 'Financial Reports', path: '/accounts/reports', icon: FileSpreadsheet },
  ],
}
